# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: A Collection of Random Things
subtitle: 'Things I come up sometime'
description: 'This guy is very lazy but he wants to fill this blank.'
keywords:
author: Roger Everett
language: en
timezone: 'America/New_York'

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: http://evertqin.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  auto_detect: false
  line_number: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/evertqin/evertqin.github.io
  # example, https://github.com/hexojs/hexojs.github.io
  branch: master



#################################################################
###################### NexT Configuration #######################
#################################################################

theme_config:

  # ============================================================= #
  # ============= Theme Core Configuration Settings ============= #
  # ============================================================= #

  custom_file_path:
    # sidebar: source/_data/sidebar.swig
    # footer: source/_data/footer.swig
    # variable: source/_data/variables.styl
    # style: source/_data/styles.styl


  # ============================================================= #
  # ================= Site Information Settings ================= #
  # ============================================================= #

  footer:
    since: 2014
    icon:
      name: fa fa-heart
      animated: true
      color: "#808080"
    copyright: NexT
    powered: false

  creative_commons:
    license: by-nc-sa
    sidebar: true


  # ============================================================= #
  # ====================== Scheme Settings ====================== #
  # ============================================================= #

  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini

  darkmode: true


  # ============================================================= #
  # ======================= Menu Settings ======================= #
  # ============================================================= #

  menu:
    home: / || fa fa-bullhorn

    # Docs:
    #   default: /docs/ || fa fa-book

    #   Getting Started:
    #     default: /getting-started/ || fa fa-flag
    #     Installation: /installation.html || fa fa-download
    #     Deployment: /deployment.html || fa fa-upload
    #     Configuration: /configuration.html || fa fa-wrench
    #     Update from 5.x: /update-from-v5.html || fa fa-retweet

    #   Theme Settings:
    #     default: /theme-settings/ || fa fa-star
    #     Footer: /footer.html || far fa-sun
    #     Sidebar: /sidebar.html || fa fa-bars
    #     Posts: /posts.html || far fa-edit
    #     Custom Pages: /custom-pages.html || far fa-file-alt
    #     Custom Files: /custom-files.html || far fa-file
    #     SEO: /seo.html || fa fa-external-link-square-alt
    #     Front Matter: /front-matter.html || fa fa-heading

    #   Third Party Services:
    #     default: /third-party-services/ || fa fa-plug
    #     Math Equations: /math-equations.html || fa fa-superscript
    #     Comment Systems: /comments.html || far fa-comments
    #     Statistics and Analytics: /statistics-and-analytics.html || fa fa-chart-bar
    #     Post Widgets: /post-widgets.html || fa fa-share-square
    #     Search Services: /search-services.html || fa fa-search-plus
    #     Chat Services: /chat-services.html || fa fa-comment
    #     External Libraries: /external-libraries.html || fa fa-puzzle-piece

    #   Tag Plugins:
    #     default: /tag-plugins/ || fa fa-rocket
    #     Note: /note.html || fa fa-comment
    #     Tabs: /tabs.html || fa fa-columns
    #     PDF: /pdf.html || far fa-file-pdf
    #     Mermaid: /mermaid.html || fa fa-tasks
    #     Label: /label.html || fa fa-font
    #     Video: /video.html || fa fa-video
    #     Button: /button.html || fa fa-square
    #     Caniuse: /caniuse.html || fa fa-signal
    #     Group Pictures: /group-pictures.html || far fa-file-image

    #   Advanced Settings: /advanced-settings.html || fa fa-cogs
    #   FAQ's: /faqs.html || fa fa-life-ring
    #   Troubleshooting: /troubleshooting.html || fa fa-bug
    archives: /archives/ || fa fa-archive
    #sitemap: /sitemap.xml || fa fa-sitemap
    #commonweal: /404/ || fa fa-heartbeat

  menu_settings:
    icons: true
    badges: true


  # ============================================================= #
  # ===================== Sidebar Settings ====================== #
  # ============================================================= #

  sidebar:
    position: left
    display: post
    padding: 18
    offset: 12
    onmobile: true

  avatar:
    url: /images/apple-touch-icon-next.png
    rounded: true

  social:
    GitHub: https://github.com/theme-next || fab fa-github
    E-Mail: mailto:support@theme-next.org || fa fa-envelope
    RSS: /atom.xml || fa fa-rss

    Gitter: https://gitter.im/theme-next || fab fa-github-alt
    Riot: https://riot.im/app/#/room/#NexT:matrix.org || fa fa-comment-dots

    Telegram: https://t.me/theme_next || fab fa-telegram

  social_icons:
    enable: true
    icons_only: true
    transition: true

  toc:
    enable: true
    number: true
    wrap: true


  # ============================================================= #
  # ======================= Post Settings ======================= #
  # ============================================================= #

  post_meta:
    updated_at:
      enable: false

  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: true

  post_edit:
    enable: true
    url: https://github.com/theme-next/theme-next.org/edit/source/source/


  # ============================================================= #
  # ==================== Misc Theme Settings ==================== #
  # ============================================================= #

  mobile_layout_economy: true

  codeblock:
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  # https://theme-next.js.org/docs/theme-settings/miscellaneous
  # See: https://github.com/chriskempson/tomorrow-theme

    theme:
      light: vs
      dark: tomorrow-night
    prism:
      light: prism
      dark: prism-dark

    copy_button:
      enable: true
      show_result: true
      style: default

  back2top:
    enable: true
    sidebar: false
    scrollpercent: true

  github_banner:
    enable: true
    permalink: https://github.com/theme-next/hexo-theme-next
    title: Fork NexT on GitHub


  # ============================================================= #
  # ======================= SEO Settings ======================== #
  # ============================================================= #

  index_with_subtitle: true

  exturl: true

  yandex_site_verification: 3ac9ae36ddebb425


  # ============================================================= #
  # =============== Third Party Services Settings =============== #
  # ============================================================= #

  math:
    per_page: true
    mathjax:
      enable: true

  pjax: true

  mediumzoom: true

  lazyload: true


  # ============================================================= #
  # =================== Comments and Widgets ==================== #
  # ============================================================= #

  comments:
    lazyload: true

  disqus:
    enable: true
    shortname: theme-next
    count: true


  # ============================================================= #
  # ================= Statistics and Analytics ================== #
  # ============================================================= #


  # ============================================================= #
  # ====================== Search Services ====================== #
  # ============================================================= #

  local_search:
    enable: true
    trigger: auto
    top_n_per_article: 1


  # ============================================================= #
  # ======================== Tag Plugins ======================== #
  # ============================================================= #

  note:
    style: simple
    icons: true
    light_bg_offset: -3

  tabs:
    transition:
      tabs: true
      labels: true


  # ============================================================= #
  # ==================== External Libraries ===================== #
  # ============================================================= #

  motion:
    enable: false

  vendors:
    anime: //cdn.jsdelivr.net/npm/animejs@3/lib/anime.min.js
    fontawesome: //cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css
    pjax: //cdn.jsdelivr.net/gh/theme-next/theme-next-pjax@0/pjax.min.js